// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: mp-metrics
:page-layout: guide
:page-duration: 20 minutes
:page-description: Learn how to provide system and application metrics from a microservice using MicroProfile Metrics.
:page-tags: ['Metrics' , 'MicroProfile' , 'CDI', '@Timed', '@Counted', '@Gauge', 'REST']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
= Providing metrics from a microservice

Learn how to provide system and application metrics from a microservice using MicroProfile Metrics.

== What you'll learn

You will learn how to use MicroProfile Metrics to provide metrics from a RESTful application.
Having metrics in an application serves to pinpoint issues and provides long term trend data for
capacity planning and pro-active discovery of issues such as disk usage growing without bounds. They can
also help those scheduling systems to decide when to scale the application to run on more or fewer machines.

MicroProfile Metrics provides an endpoint where you can get the metrics
results as a plain text format. This endpoint has three scopes: base, application and vendor.
For the purpose of this guide, the focus is on the application scope. The metadata of the metrics in
any scope has fields such as unit, type, description, etc. The type can be a counter, gauge,
meter, histogram and timer. You will use the counter, gauge and timer types in your application.

The application that you will be working with is an `inventory` service, which stores the information
about various JVMs that run on different systems. Whenever a request is made to the `inventory`
service to retrieve the JVM system properties of a particular host, the `inventory` service
communicates with the `system` service on that host to get these system properties.
The system properties are then stored and returned.

You will apply the 'metrics type annotations' to the inventory application in order to provide metrics
at the application scope.

// =================================================================================================
// Getting Started
// =================================================================================================

== Getting started

The fastest way to work through this guide is to clone the Git repository and use the starting project
that is provided in the `start` directory. To do this, run the following commands:

[subs="attributes"]
----
git clone https://github.com/OpenLiberty/draft-guide-microprofile-metrics.git
cd draft-guide-microprofile-metrics/start
----

// =================================================================================================
// Try what you'll build
// =================================================================================================

=== Try what you'll build

The `finish` directory in the root of this guide contains the finished metrics implementation
for the application. Feel free to give it a try before you proceed with building your own.

To try out the application, first navigate to the `finish` directory and then run the following.
Maven aims to build the application and run it inside Open Liberty:

```
mvn install liberty:start-server
```

Point your browser to `http://localhost:9080/inventory/systems`. As you can see, there are no
hosts registered currently since you have just started the application. Point to
`http://localhost:9080/metrics` MicroProfile Metrics endpoint. From here, you can see
the standard metrics, and also includes the application metrics, in Prometheus format.
Point to `http://localhost:9080/metrics/application` to see application metrics only. The
application metrics will not show up if you do not point your browser first to
`http://localhost:9080/inventory/systems`. This is because these metrics are application related.

Once you are done checking out the application, stop the Open Liberty server:

```
mvn liberty:stop-server
```

Now, navigate back to the `start` directory to begin.

// =================================================================================================
// Adding Microprofile Metrics to inventory application
// =================================================================================================

== Adding Microprofile Metrics to inventory application

Begin by enabling the MicroProfile Metrics in your `pom.xml` file. This feature allows you to
use the MicroProfile Metrics API to provide the metrics from your RESTful services.

Navigate to the `/start/pom.xml` file and add the required dependency:

[source, xml, indent=0]
----
include::finish/pom.xml[tags=metrics]
----

You also need to set the system property `javax.net.ssl.trustStore` in the `pom.xml` to point to
the SSL certificate:

[source, xml, indent=0]
----
include::finish/pom.xml[tags=system-props]
----

The `mpMetrics-1.0` feature provides `http://localhost:9080/metrics` endpoint.

This feature also requires you to secure this endpoint.
To do this, open `start/src/main/liberty/config/server.xml`:

[source, xml, indent=0]
----
include::finish/src/main/liberty/config/server.xml[tags=server]
----

The `quickStartSecurity` and `keyStore` configurations elements allow you to add a basic security
to this application. Use these credentials to view the metrics endpoint when you browse it.

Proceed with the section below to add the metrics using the annotations.

// =================================================================================================
// Adding metrics to the @timed and @counted annotations
// =================================================================================================

=== Adding the @timed and @counted annotations

Create the class `/start/src/main/java/io/openliberty/guides/inventory/InventoryManager.java`:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryManager.java[tags=InventoryManager]
----

As you can see, there are two metrics annotations:

`@Timed` is a metric annotation that applies on the `get()` method to track how frequently the method is
invoked and also how long it took for the invocation to complete. Most of the annotations are
followed by fields that correspond to metadata fields and some of them are provided by default
and others are just optional. Timer is a complex metric type comprised of multiple key/values.
The `name` field sets the name of the metric. If not explicitly given, the name of the annotated
method is used. For the `@Timed` annotation the default value of `unit` is `seconds`. The
`description` field is optional and it provides a brief description of the purpose of the metric
annotation.

`@Counted` is a metric annotation that applies on the `list()` method to count how many times the list of systems
method is requested. In other words, how many times we display the current contents of the
inventory by going to `http://localhost:9080/inventory/systems`. The `absolute` field is used to make the name of
this annotation take the name of the method. Like the previous annotation, this annotation has
a `description` field too. The `monotonic` field has a default value `false`
which means that the counter is incremented before the annotated method returns, counting current
invocations of the annotated method. This is not what we want in this case, thus set the value
to `true`.

=== Adding the @Gauge annotation

Create the class `/start/src/main/java/io/openliberty/guides/inventory/model/InventoryList.java`:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/inventory/model/InventoryList.java[tags=InventoryList]
----

The `@Gauge` annotation on the `getTotal()` method tracks the number of systems stored
in the inventory (or tracks the inventory size). A system is stored in the inventory when you visit
`http://localhost:9080/inventory/systems/localhost`. The `unit` field must be specified because there
is no default value for this annotation. The `name` and `description` are optional like in
the previous two annotations.

These three annotations are registered by default to the singleton object `MetricRegistry`.
Through this object, they send their metadata or metrics to `http://localhost:9080/metrics/application`.

This application is provided for you in this guide.
If you want to learn how to create a RESTful application, see
https://openliberty.io/guides/rest-intro.html[Creating a RESTful web service].

// =================================================================================================
// Building and running the application
// =================================================================================================

== Building and running the application

To build the application, run the Maven install goal from the command line:

```
  mvn install
```

This goal builds the application and creates a .war file in the target directory and also
configures and installs Open Liberty into the target/liberty/wlp directory.

Next, run the Maven liberty:start-server goal:

```
  mvn liberty:start-server
```

This goal starts an Open Liberty server instance. Your Maven `pom.xml` is already configured to
start the application in this server instance.

Once the server is running, you can find the metrics endpoint showing useful JVM/server base
details at the following URL:

* `http://localhost:9080/metrics`

After you point your browser to `http://localhost:9080/inventory/systems`, you can find specific
metrics about your application at the following URL:

* `http://localhost:9080/metrics/application`

If you make changes to the code, use the Maven package command to rebuild the application and have
the running Open Liberty server pick them up automatically:

```
  mvn package
```

To stop the Open Liberty server, run the Maven liberty:stop-server goal:

```
  mvn liberty:stop-server
```

// =================================================================================================
// Testing the metrics
// =================================================================================================

== Testing the metrics

While you can test your application manually, you should rely on automated tests since they will
trigger a failure whenever a code change introduces a defect. JUnit and the JAX-RS Client API
provide a simple environment for you to write tests.

Begin by creating a test class `start/src/test/java/it/io/openliberty/guides/metrics/MetricsTest.java`:

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/metrics/MetricsTest.java[tags=MetricsTest]
----

The `@BeforeClass` annotation is placed on a method that executes before any of the test cases. In
this case, the `oneTimeSetup()` method retrieves the port number for the Open Liberty server and builds
a base URL string that is used throughout the tests.

The `@Before` and `@After` annotations are placed on methods that execute before and after every
test case. These methods are generally used to perform any setup and teardown tasks.
In this case, the `setup()` method creates a JAX-RS client which makes HTTP requests to the
inventory service. This client must also be registered with a JSON-P provider (JsrJsonpProvider)
to process JSON resources. The `teardown()` simply destroys this client instance.

Let’s break down the test cases:

* `testGetPropertiesTime()` sends a request to `http://localhost:9080/inventory/systems/localhost`
then verifies the `200` response code is returned using `connectToEndpoint()` private method. Next,
it makes a connection to `http://localhost:9080/metrics/application` to get the content of the
metrics as a plain text. After that, it asserts if the time needed to get the system properties for
`localhost` is less than two seconds, using `validateMetric()` method. This test case tests
`@Timed` annotation.

* `testListCount()` sends a request to `http://localhost:9080/inventory/systems` using
`connectToEndpoint()` method. Next, it asserts if `list()` method in `InventoryManager`
class was invoked once using `validateMetric()` method. This test case tests `@Counted` annotation.

* `testInventorySize()` sends a request to `http://localhost:9080/inventory/systems/localhost` using
`connectToEndpoint()` method. Because of this request, the inventory grows in size resulting in
`getHostCount()` method in `InventoryManager` class to return one host which represent the
localhost. It then asserts that using `validateMetric()` method.

To force these test cases to execute in a particular order, put them in a `testSuite()` method and
label it with a `@Test` annotation so that it automatically executes when your test class run.

=== Running the tests

Go to `start` directory and run `mvn clean install`. You should see two tests pass with the
following results:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.metrics.MetricsTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.778 sec - in it.io.openliberty.guides.metrics.MetricsTest
Running it.io.openliberty.guides.inventory.EndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.128 sec - in it.io.openliberty.guides.inventory.EndpointTest

Results :

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
```

To see whether the tests detect a failure, change the assertion value(s) in `validateMetric()` method.
`MetricsTest.java` file. Re-run the Maven build. You will see a test failure occur.

// =================================================================================================
// Great work! You're done!
// =================================================================================================

== Great work! You're done!

You have learned how to provide system and application metrics from microservices. Then you wrote tests to validate that.

You can continue to try one of the related guides, which demonstrate new technologies that you can learn and
expand on top what you built in this guide.

include::{common-includes}/finish.adoc[]
