// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: microprofile-metrics
:page-layout: guide
:page-duration: 15 minutes
:page-releasedate: 2018-03-15
:page-description: Learn how to provide system and application metrics from a microservice with MicroProfile Metrics.
:page-tags: ['Metrics' , 'MicroProfile' , 'CDI', '@Timed', '@Counted', '@Gauge', 'REST', 'microservices']
:page-permalink: /guides/{projectid}
:page-related-guides: ['rest-intro', 'microprofile-health', 'cdi-intro']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
= Providing metrics from a microservice

You'll explore how to provide system and application metrics from a microservice with MicroProfile Metrics.

// =================================================================================================
// What you'll learn
// =================================================================================================

== What you'll learn

You will learn how to use MicroProfile Metrics to provide metrics from a microservice. You can monitor 
metrics to determine the performance and health of a service. You can also use them to pinpoint issues,
collect data for capacity planning, or to decide when to scale a service to run with more or fewer
resources.

The application that you will work with is an `inventory` service that stores information about various
systems. The `inventory` service communicates with the `system` service on a particular host to retrieve
its system properties when necessary.

You will use annotations provided by MicroProfile Metrics to instrument the `inventory` service to
provide application-level metrics data. You will add counter, gauge and timer metrics to the service.

You will also check well-known REST endpoints defined by MicroProfile Metrics to review the metrics
data collected. Monitoring agents can access these endpoints to collect metrics.

// =================================================================================================
// Getting Started
// =================================================================================================

include::{common-includes}/gitclone.adoc[]

// =================================================================================================
// Try what you'll build
// =================================================================================================

=== Try what you'll build

The `finish` directory contains the finished implementation for the application. You can try it out
before you build your own.

To try the application, navigate to the `finish` directory and run the following command:

```
mvn install liberty:start-server
```

Maven builds the application and runs it inside Open Liberty.

Point your browser to the `http://localhost:9080/inventory/systems` URL to access the `inventory`
service. Because you just started the application, the inventory is currently empty. Then, access the
`http://localhost:9080/inventory/systems/localhost` URL to add the localhost host into the inventory.

Access the `inventory` service i.e. the `http://localhost:9080/inventory/systems` URL at least once
for application metrics to be collected. Otherwise, the metrics will not appear.

Next, point your browser to the `https://localhost:9443/metrics` MicroProfile Metrics endpoint. Login
as the `confAdmin` user with `microprofile` as the password. You can see both the system and application
metrics in a text format.

To see only the application metrics, point your browser to `https://localhost:9443/metrics/application`.

Sample outputs for the `@Timed`, `@Gauge`, and `@Counted` metrics:

[source, role="no_copy"]
----
# TYPE application:io_openliberty_guides_inventory_inventory_manager_get_properties_time_rate_per_second gauge
application:io_openliberty_guides_inventory_inventory_manager_get_properties_time_rate_per_second 0.08662540922169244
# HELP application:io_openliberty_guides_inventory_inventory_manager_get_properties_time_seconds Time needed to get the properties of a system from the given hostname
----
[source, role="no_copy"]
----
# TYPE application:io_openliberty_guides_inventory_inventory_manager_inventory_size gauge
# HELP application:io_openliberty_guides_inventory_inventory_manager_inventory_size Number of systems in the inventory
application:io_openliberty_guides_inventory_inventory_manager_inventory_size 1
----
[source, role="no_copy"]
----
# TYPE application:list counter
# HELP application:list Number of times the list of systems method is requested
application:list 1
----

When you're done with the application, stop the Open Liberty server with the following command:

```
mvn liberty:stop-server
```

Now, navigate back to the `start` directory to begin.

// =================================================================================================
// Adding MicroProfile Metrics to the inventory service
// =================================================================================================

== Adding MicroProfile Metrics to the inventory service

The MicroProfile Metrics API was added as a dependency to your `pom.xml` file. Look for the dependency with
the `org.eclipse.microprofile.metric` group ID. This dependency enables you to use MicroProfile Metrics
API in your code to provide metrics from your microservices.

Next, create a `src/main/liberty/config/server.xml` file:

[source, xml, indent=0]
----
include::finish/src/main/liberty/config/server.xml[tags=server]
----

The `mpMetrics-1.0` feature enables MicroProfile Metrics support in Open Liberty. Note that this
feature requires SSL and the configuration has been provided to you.

The `quickStartSecurity` and `keyStore` configuration elements provide basic security to secure the
server. When you visit the `/metrics` endpoint, you use the credentials defined in the server
configuration to login to view the data.

// =================================================================================================
// Adding the annotations
// =================================================================================================

=== Adding the annotations

Create the `InventoryManager` class in the
`src/main/java/io/openliberty/guides/inventory/InventoryManager.java` file:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryManager.java[tags=InventoryManager]
----

Apply the `@Timed` annotation to the `get()` method to track how frequently the method is
invoked and also how long it takes for the invocation to complete. This annotation has these
metadata fields:

|===
|`name` | Optional; Use this to name of the metric
|`description` | Optional; Use this to describe the purpose of the metric
|===

Apply the `@Counted` annotation to the `list()` method to count how many times the
`http://localhost:9080/inventory/systems` URL is accessed. Note the additional metadata field:

|===
| `monotonic` | Set to `true` to count the total number of invocations of the annotated method i.e.
the total number of accesses.
|===

Apply the `@Gauge` annotation to the `getTotal()` method to track the number of systems that are stored in
the inventory. Note that when the value of the gauge is retrieved, the underlying `getTotal()` method
is called to return the size of the inventory.

Additional information about these annotations, relevant metadata fields and more is available at
the https://microprofile.io/project/eclipse/microprofile-metrics[MicroProfile website].

// =================================================================================================
// Building and running the application
// =================================================================================================

include::{common-includes}/mvnbuild.adoc[]

Point your browser to the `https://localhost:9443/metrics` URL to review the all available metrics
that has been enabled through MicroProfile Metrics. Login with `confAdmin` and `microprofile`. You
see only the system metrics because the server just started and the `inventory` service has not been
accessed.

Next, point your browser to the `http://localhost:9080/inventory/systems` URL. Reload
`https://localhost:9443/metrics` or you can access the application metrics only with the URL, 
`https://localhost:9443/metrics/application`.

include::{common-includes}/mvnpackage.adoc[]

// =================================================================================================
// Testing the metrics
// =================================================================================================

== Testing the metrics

You can test your application manually, but automated tests ensure code quality as they trigger a
failure whenever a code change introduces a defect. JUnit and the JAX-RS Client API provide a simple
environment for you to write tests.

First, create a `src/test/java/it/io/openliberty/guides/metrics/MetricsTest.java` test class:

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/metrics/MetricsTest.java[tags=MetricsTest]
----

* The `testGetPropertiesTime()` test case validates the `@Timed` metric. It sends a request to the 
`http://localhost:9080/inventory/systems/localhost` URL to access the `inventory` service and add
the `localhost` host to the inventory. Next, the test case makes a connection to the 
`https://localhost:9443/metrics/application` URL to retrieve application metrics as plain text.
It then uses the `validateMetric()` method to assert whether the time that is needed to retrieve
the system properties for `localhost` is less than 4 seconds.

* The `testListCount()` test case validates the `@Counted` metric. The test case sends a request to the 
`http://localhost:9080/inventory/systems` URL to retrieve the whole inventory and then, it asserts
that this endpoint is only accessed once.

* The `testInventorySize()` test case validates the `@Gauge` metric. The test case first ensures
that the  `localhost` host is in the inventory. It then looks for the `@Gauge` metric and asserts
that the inventory size is equal to one.

The `oneTimeSetup()` method retrieves the port number for the server and builds a base URL string
to setup the tests. Apply the `@BeforeClass` annotation to this method to execute it before any of
the test cases.

The `setup()` method creates a JAX-RS client that makes HTTP requests to the `inventory` service.
Register this client with a `JsrJsonpProvider` JSON-P provider to process JSON resources. The
`teardown()` method destroys this client instance. Apply the `@Before` and `@After` annotations to
these methods respectively so that they execute before and after every test case. Apply these annotations
to methods generally used to perform any setup and teardown tasks before and after a test.

To execute the test cases in a particular order, put them in a `testSuite()` method.
Label the method with the `@Test` annotation, which automatically executes when your test class runs.

In addition, a few endpoint tests `src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointTest.java`
and `src/test/java/it/io/openliberty/guides/system/SystemEndpointTest.java` are provided for you to
test the basic functionality of the `inventory` and `system` services. If a test failure occurs, then you might have
introduced a bug into the code.

// =================================================================================================
// Running the tests
// =================================================================================================

include::{common-includes}/mvnverify.adoc[]

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.system.SystemEndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.4 sec - in it.io.openliberty.guides.system.SystemEndpointTest
Running it.io.openliberty.guides.metrics.MetricsTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.697 sec - in it.io.openliberty.guides.metrics.MetricsTest
Running it.io.openliberty.guides.inventory.InventoryEndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.264 sec - in it.io.openliberty.guides.inventory.InventoryEndpointTest

Results :

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
----

To see whether the tests detect a failure, go to the `MetricsTest.java` file and change an assertion
in the `validateMetric()` method. Rerun the Maven build. A test failure occurs.

// =================================================================================================
// Great work! You're done!
// =================================================================================================

== Great work! You're done!

You learned how to enable system and application metrics for microservices using MicroProfile Metrics
and wrote tests to validate them.

include::{common-includes}/finish.adoc[]
