// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: microprofile-metrics
:page-layout: guide
:page-duration: 15 minutes
:page-releasedate: 2018-03-09
:page-description: Learn how to provide system and application metrics from a microservice with MicroProfile Metrics.
:page-tags: ['Metrics' , 'MicroProfile' , 'CDI', '@Timed', '@Counted', '@Gauge', 'REST', 'microservices']
:page-permalink: /guides/{projectid}
:page-related-guides: ['rest-intro', 'microprofile-health', 'cdi-intro']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
= Providing metrics from a microservice

You'll explore how to provide system and application metrics from a microservice with MicroProfile Metrics.

== What you'll learn

You will learn how to use MicroProfile Metrics to provide metrics from a microservice.
Include metrics in an application to pinpoint issues, provide long-term trend data for
capacity planning, and provide proactive discovery of issues, such as disk usage growth without
bounds. Metrics can also help you schedule systems and decide when to scale the application to
run on more or fewer machines.

The application that you will work with is an `inventory` service
that stores information about various JVMs that run on different systems.
Whenever a request is made to the `inventory` service to retrieve the JVM
system properties of a particular host, the `inventory` service communicates with the `system`
service on that host to get the system properties. The system properties are then stored and returned.

MicroProfile Metrics has endpoints where you can get the metrics
results in a plain text format or JSON format. These endpoints have three scopes: `base`,
`application`, and `vendor`. The `application` scope is the focus for the `inventory` application.

The metadata of the metrics in any scope has fields, such as unit, type, description, and more.
The type can be a counter, gauge, meter, histogram, or timer. You will use the counter, gauge, and
timer types in your application.

You can instrument a microservice in different ways, such as with injection, annotations, or by using
the `MetricRegistry` directly. In this guide, you will learn how to use annotations to register
metrics to the `inventory` service.

// =================================================================================================
// Getting Started
// =================================================================================================

include::{common-includes}/gitclone.adoc[]

// =================================================================================================
// Try what you'll build
// =================================================================================================

=== Try what you'll build

The `finish` directory contains the finished metrics implementation
for the application. You can try it out before you build your own.

To try the application, navigate to the `finish` directory and run the following command:

```
mvn install liberty:start-server
```

Maven builds the application and runs it inside Open Liberty.

Point your browser to the `http://localhost:9080/inventory/systems` URL.
Because you just started the application, the inventory is currently empty. Point to the
`http://localhost:9080/inventory/systems/localhost` URL to add the localhost host into the inventory.

Next, point to the `https://localhost:9443/metrics` MicroProfile Metrics URL. Click the `Advanced`
button to proceed. Use the `confAdmin` and `microprofile` credentials to log in. You can see both
the standard metrics and the application metrics in a text format.

To see only the application metrics, point your browser to `https://localhost:9443/metrics/application`.
Because these metrics are application-related, you had to point first to the `\http://localhost:9080/inventory/systems` URL,
otherwise they will not appear. See some of the metric outputs:

[source, role="no_copy"]
----
# TYPE application:io_openliberty_guides_inventory_inventory_manager_get_properties_time_rate_per_second gauge
application:io_openliberty_guides_inventory_inventory_manager_get_properties_time_rate_per_second 0.08662540922169244
----
[source, role="no_copy"]
----
# HELP application:io_openliberty_guides_inventory_inventory_manager_get_properties_time_seconds Time needed to get the properties of a system from the given hostname
----
[source, role="no_copy"]
----
# TYPE application:io_openliberty_guides_inventory_inventory_manager_inventory_size gauge
# HELP application:io_openliberty_guides_inventory_inventory_manager_inventory_size Number of systems in the inventory
application:io_openliberty_guides_inventory_inventory_manager_inventory_size 1
# TYPE application:list counter
# HELP application:list Number of times the list of systems method is requested
application:list 1
----

When you're done with the application, stop the Open Liberty server with the following command:

```
mvn liberty:stop-server
```

Now, navigate back to the `start` directory to begin.

// =================================================================================================
// Adding Microprofile Metrics to the inventory microservice
// =================================================================================================

== Adding Microprofile Metrics to the inventory microservice

Navigate to the `pom.xml` file. In the `pom.xml` file, the MicroProfile Metrics API has been added as a
dependency to your `pom.xml` file. Look for the dependancy with the `org.eclipse.microprofile.metric` groupId. This
feature allows you to use the MicroProfile Metrics API to provide metrics from your microservices. Also in the `pom.xml`,
you will find the `javax.net.ssl.trustStore` system property variable. This variable points to the SSL certificate of the system.

Next, create a `src/main/liberty/config/server.xml` file:

[source, xml, indent=0]
----
include::finish/src/main/liberty/config/server.xml[tags=server]
----

The `mpMetrics-1.0` feature provides the `https://localhost:9443/metrics` endpoint.

The `quickStartSecurity` and `keyStore` configuration elements provide basic security to secure the endpoint. When you visit
the endpoint, you use these credentials to login in order to view the metrics.

// =================================================================================================
// Adding the annotations
// =================================================================================================

=== Adding the annotations

Create the `InventoryManager` class in the
`src/main/java/io/openliberty/guides/inventory/InventoryManager.java` file:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryManager.java[tags=InventoryManager]
----

Notice the metrics annotations added to this class:

The `@Timed` annotation applies to the `get()` method to track how frequently the method is
invoked and also how long it takes for the invocation to complete. This annotation has these
metadata fields:

|===
|`name` | Optional and sets the name of the metric
|`description` | Optional and describes the purpose of the metric annotation
|===

The `@Counted` annotation applies to the `list()` method. This annotation counts how many times you request the list of
systems methods when you visit the `http://localhost:9080/inventory/systems` URL. This URL retrieves the information for a
list of all previously registered hosts. See the additional metadata fields:

|===
| `absolute` | if `true`, it names the metric the name of the method. If `false`, it attaches the package name and class name
before the method name
| `monotonic` | if `true`, it makes the counter counts the total invocation of the annotated method. if `false`,
it makes the counter counts the current invocation of the annotated method. In another words, it makes the counter increase
only when the annotated method is called and decrease when it returns
|===

The `@Gauge` annotation on the `getTotal()` method tracks the number of systems that are stored in
the inventory. A system is stored in the inventory when you visit the
`http://localhost:9080/inventory/systems/localhost` URL to retrieve the information for a specific host.
See the additional metadata field:

|===
| `unit` | Sets the unit of the metric
|===

Note that, when the value of the gauge is retrieved, the underlying `getTotal()` annotated method is
called to return the value.

These annotations are registered by default to the `MetricRegistry` singleton object.
This object sends the metadata and metrics to the `https://localhost:9443/metrics/application`
MicroProfile Metrics endpoint, which is provided for you. Also, the `@Counted`, `@Gauge`, and
`@Timed` annotations can be placed in a service, such as the `inventory` service in the
`src/main/java/io/openliberty/guides/inventory/InventoryResource.java` file.

// =================================================================================================
// Building and running the application
// =================================================================================================

include::{common-includes}/mvnbuild.adoc[]

Point your browser to the `https://localhost:9443/metrics` URL to find the metrics that show JVM
and server base details.

Next, point your browser to `http://localhost:9080/inventory/systems`. Then, you can find
specific metrics about your application at the `https://localhost:9443/metrics/application` URL.

include::{common-includes}/mvnpackage.adoc[]

// =================================================================================================
// Testing the metrics
// =================================================================================================

== Testing the metrics

You can test your application manually, but automated tests
trigger a failure whenever a code change introduces a defect. JUnit and the JAX-RS Client API
provide a simple environment for you to write tests.

First, create a `src/test/java/it/io/openliberty/guides/metrics/MetricsTest.java` test class:

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/metrics/MetricsTest.java[tags=MetricsTest]
----

Place the `@BeforeClass` annotation on a method that executes before any of the test cases. In
this case, the `oneTimeSetup()` method retrieves the port number for the server and builds
a base URL string that is used throughout the tests.

Place the `@Before` and `@After` annotations on methods that execute before and after every
test case. These methods are generally used to perform any setup and teardown tasks.
In this case, the `setup()` method creates a JAX-RS client that makes HTTP requests to the
inventory service. Register this client with a `JsrJsonpProvider` JSON-P provider
to process JSON resources. The `teardown()` method destroys this client instance.

See the break down of the test cases:

* The `testGetPropertiesTime()` test case is used to test the `@Timed` annotation. This test case
sends a request to the `http://localhost:9080/inventory/systems/localhost` URL. The test verifies
the `200` response code, which is returned with the `connectToEndpoint()` private method. Next, the
test case makes a connection to the `https://localhost:9443/metrics/application` URL to get the
content of the metrics as plain text. The test case then uses the `validateMetric()` method to
assert whether the time that is needed to get the system properties for `localhost` is less than 4
seconds.

* The `testListCount()` test case is used to test the `@Counted` annotation. This test case uses the
`connectToEndpoint()` method to send a request to the `http://localhost:9080/inventory/systems` URL.
Next, the test case uses the `validateMetric()` method to assert whether the `list()` method in the
`InventoryManager` class was invoked once.

* The `testInventorySize()` test case is used to test the `@Gauge` annotation. This test case uses the
`connectToEndpoint()` method to send a request to the `http://localhost:9080/inventory/systems/localhost`
URL. Because of the request, the `getTotal()` method in the `InventoryManager` class returns a value of one,
which represents the localhost. In another words, the inventory size increases by one due to the request.
Then the `validateMetric()` method asserts if the inventory size is equal to one.

To execute the test cases in a particular order, put them in a `testSuite()` method.
Label the method with the `@Test` annotation, which automatically executes when your test class runs.

In addition, a few endpoint tests `src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointTest.java`
and `src/test/java/it/io/openliberty/guides/system/SystemEndpointTest.java` are provided for you to
test the basic functionality of the `inventory` and `system` services. If a test failure occurs, then you might have
introduced a bug into the code.

// =================================================================================================
// Running the tests
// =================================================================================================

include::{common-includes}/mvnverify.adoc[]

[source, role="no_copy"]
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.system.SystemEndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.4 sec - in it.io.openliberty.guides.system.SystemEndpointTest
Running it.io.openliberty.guides.metrics.MetricsTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.697 sec - in it.io.openliberty.guides.metrics.MetricsTest
Running it.io.openliberty.guides.inventory.InventoryEndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.264 sec - in it.io.openliberty.guides.inventory.InventoryEndpointTest

Results :

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0

To see whether the tests detect a failure, go to the `MetricsTest.java` file and change the assertion values in the `validateMetric()` method. Rerun the Maven build. A test failure occurs.

// =================================================================================================
// Great work! You're done!
// =================================================================================================

== Great work! You're done!

You learned how to provide system and application metrics from microservices and wrote tests to validate them.

include::{common-includes}/finish.adoc[]
