// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: mp-metrics
:page-layout: guide
:page-duration: 20 minutes
:page-description: Learn how to use MicroProfile Metrics in an application
:page-tags: ['Metrics' , 'MicroProfile' , 'REST']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
= Providing metrics from a microservice

Learn how to provide system and application metrics from a microservice using MicroProfile Metrics.

// =================================================================================================
//  What you'll learn
// =================================================================================================

== What you'll learn

You will learn how to use MicroProfile Metrics feature to provide metrics from a RESTful application.
The great benefit from having metrics in an application is that it serve to pinpoint issues, provide
long term trend data for capacity planning and pro-active discovery of issues (e.g. disk u
sage growing without bounds). They can also help those scheduling systems decide when to scale
the application to run on more or fewer machines.

The MicroProfile Metrics feature provides an endpoint that you can get the metrics results as a
plain text format. This endpoint has three scopes: base, application and vendor. For the purpose
of this guide, the application scope is used. The metadata of the metrics in any scope has a unit,
type, description and other things. The type can be a counter, gauge, meter, histogram and timer.

You will make the manager class, `InventoryManager`, in the inventory application provide
metrics at the application scope. This application is provided for you in this guide.
If you want to learn how to create a RESTful application, see
https://openliberty.io/guides/rest-intro.html[Creating a RESTful web service].

After starting the application, you will be able to access two microservices to test their availability:

* `\http://localhost:9080/inventory/hosts` retrieves the information for a list of all previously
registered hosts.

* `\http://localhost:9080/metrics` exposes required JVM/server base and application
specific metrics. [Why we explaining base scope ? not sure if we are including that]

// =================================================================================================
// Getting Started
// =================================================================================================

// include::{common-includes}/gitclone.adoc[]

== Getting started

The fastest way to work through this guide is to clone the git repository and use the starting project
that is provided in the `start` directory. To do this, run the following commands:

[subs="attributes"]
----
git clone https://github.com/openliberty/guide-mp-metrics.git
cd guide-mp-metrics/start
----

// =================================================================================================
// Try what you'll build
// =================================================================================================

=== Try what you'll build

The `finish` directory in the root of this guide contains the finished metrics implementation
for the application. Feel free to give it a try before you proceed with building your own.

To try out the application, first navigate to the `finish` directory and then execute the following.
Maven aims to build the application and run it inside Open Liberty:

```
mvn install liberty:start-server
```
First, point your browser to `\http://localhost:9080/inventory/hosts`. As you can see, there are no
registered hosts currently since you just started the application. Next, go to the MicroProfile
Metrics endpoint: `\http://localhost:9080/metrics` [again base?]. From here, you can see the required base metrics
which describe a set of metrics that all MicroProfile-compliant servers have to provide. For
specific application metrics go to `\http://localhost:9080/metrics/application`. This endpoint
will not expose metrics if you don't point your browser first to `\http://localhost:9080/inventory/hosts`.

Once you are done checking out the application, stop the Open Liberty server:

```
mvn liberty:stop-server
```

Now, navigate back to the `start` directory to begin.

// =================================================================================================
// Adding Microprofile Metrics to inventory application
// =================================================================================================

== Adding Microprofile Metrics to inventory application

Begin by enabling the MicroProfile Metrics feature in your pom.xml file. This feature allows you to use the
MicroProfile Metrics API to provide the metrics from your RESTful services.

Navigate to the start/pom.xml file and add the required dependency:

```
link:finish/pom.xml[]
```

Proceed with the section below to add metrics to InventoryManager.

// =================================================================================================
// Adding metrics to InventoryManager bean
// =================================================================================================

=== Adding metrics to InventoryManager bean

Open `InventoryManager.java` class in /start/src/main/java/io/openliberty/guides/inventory/

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryManager.java[tags=InventoryManager]
----

As you can see, the `@Timed` annotation for `get()` method does that ...( and also describe each attribute in the annotation)

The `@Counted` annotation for `list()` method does that ...( and also describe each attribute in the annotation)

The `@Gauge` annotation for `getHostCount()` method ... same

These three annotations are registered by default to the singleton object `MetricRegistry`.
They send their metadata or metrics to the endpoint `metrics/application` through this object.
[can be modified]

// =================================================================================================
// Building and running the application
// =================================================================================================

== Building and running the application

To build the application, run the Maven install goal from the command line:

```
  mvn install
```

This goal builds the application and creates a .war file in the target directory and also
configures and installs Open Liberty into the target/liberty/wlp directory.

Next, run the Maven liberty:start-server goal:

```
  mvn liberty:start-server
```

This goal starts an Open Liberty server instance. Your Maven pom.xml is already configured to
start the application in this server instance.

Once the server is running, you can find the metrics endpoint showing useful JVM/server base
details at the following URL:

* `\http://localhost:9080/metrics` [[again base?]

After you point your browser to `\http://localhost:9080/inventory/hosts` you can also find specific
metrics about your application at the following URL:

* `\http://localhost:9080/metrics/application`

If you make changes to the code, use the Maven package command to rebuild the application and have
the running Open Liberty server pick them up automatically:

```
  mvn package
```

To stop the Open Liberty server, run the Maven liberty:stop-server goal:

```
  mvn liberty:stop-server
```

// =================================================================================================
// Testing the application
// =================================================================================================

== Testing the metrics

While you can test your application manually, you should rely on automated tests since they will
trigger a failure whenever a code change introduces a defect. JUnit and the JAX-RS Client API provide
a simple environment for you to write tests.

Begin by creating a test class `src/test/java/it/io/openliberty/guides/metrics/MetricsTest.java`:

[source, java, indent=0]
```
link::finish/src/test/java/it/io/openliberty/guides/metrics/MetricsTest.java[]
```
The `@BeforeClass` annotation is placed on a method that executes before any of the test cases. In
this case, the oneTimeSetup method retrieves the port number for the Open Liberty server and builds
a base URL string that is used throughout the tests.

The `@Before` and `@After` annotations are placed on methods that execute before and after every test
case. These methods are generally used to perform any setup and teardown tasks.
In this case, the `setup()` method creates a JAX-RS client which makes HTTP requests to the inventory
service. This client must also be registered with a JSON-P provider (JsrJsonpProvider) to process JSON
resources. `The teardown()` simply destroys this client instance.

There are few test case methods annotated with `@Test` to test the functionality of the inventory
application after adding Microprofile Metrics.

* The `testListCount()` method verifies that the correct number of requests to
`\http://localhost:9080/inventory/hosts` is counted.

* The `testHostsNumber()` method verifies that the correct number of hostnames is being added to
the `\http://localhost:9080/inventory/hosts`.

* The `testGetPropertiesTime()` method verifies that the time for executing the request is being
measured.

These two methods were used in the above :

* `connectToEndpoint()` method which makes a GET request to the given URL

* `validateAMetric()` method which asserts that the given metric's value is correct
otherwise it throws an `AssertionError`

(please try to combine and explain these methods a bit more in the first test.
Then u can reference these methods in the other two tests). Explain them briefly and quickly step by step i.e.
This test case does that first then that using that method ... then it does that and that using that method ...
up to u.

also if  u wanna call them helper methods , u will need to create a new util class called MetricsTestUti.java


== Running the tests

Go to `start` directory and run `mvn clean install`. You should see two tests pass with the following
results:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.metrics.MetricsTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.778 sec - in it.io.openliberty.guides.metrics.MetricsTest
Running it.io.openliberty.guides.inventory.EndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.128 sec - in it.io.openliberty.guides.inventory.EndpointTest

Results :

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
```

// =================================================================================================
// Great work! You're done!
// =================================================================================================

== Great work! You're done!

include::{common-includes}/finish.adoc[]
