// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: microprofile-metrics
:page-layout: guide
:page-duration: 15 minutes
:page-releasedate: 2018-03-15
:page-description: Learn how to provide system and application metrics from a microservice with MicroProfile Metrics.
:page-tags: ['Metrics' , 'MicroProfile' , 'CDI', '@Timed', '@Counted', '@Gauge', 'REST', 'microservices']
:page-permalink: /guides/{projectid}
:page-related-guides: ['rest-intro', 'microprofile-health', 'cdi-intro']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
= Providing metrics from a microservice

You'll explore how to provide system and application metrics from a microservice with MicroProfile Metrics.

// =================================================================================================
// What you'll learn
// =================================================================================================

== What you'll learn

You will learn how to use MicroProfile Metrics to provide metrics from a microservice. You can monitor
metrics to determine the performance and health of a service. You can also use them to pinpoint issues,
collect data for capacity planning, or to decide when to scale a service to run with more or fewer
resources.

The application that you will work with is an `inventory` service that stores information about various
systems. The `inventory` service communicates with the `system` service on a particular host to retrieve
its system properties when necessary.

You will use annotations provided by MicroProfile Metrics to instrument the `inventory` service to
provide application-level metrics data. You will add counter, gauge, and timer metrics to the service.

You will also check well-known REST endpoints that are defined by MicroProfile Metrics to review
the metrics data collected. Monitoring agents can access these endpoints to collect metrics.

// =================================================================================================
// Getting Started
// =================================================================================================

include::{common-includes}/gitclone.adoc[]

// =================================================================================================
// Try what you'll build
// =================================================================================================

=== Try what you'll build

The `finish` directory contains the finished implementation for the application. You can try it out
before you build your own.

To try the application, navigate to the `finish` directory and run the following command:

```
mvn install liberty:start-server
```

Maven builds the application and runs it inside Open Liberty.

Point your browser to the `http://localhost:9080/inventory/systems` URL to access the `inventory`
service. Because you just started the application, the inventory is currently empty. Then, access the
`http://localhost:9080/inventory/systems/localhost` URL to add the localhost into the inventory.

Access the `inventory` service at the `http://localhost:9080/inventory/systems` URL at least once
for application metrics to be collected. Otherwise, the metrics will not appear.

Next, point your browser to the `https://localhost:9443/metrics` MicroProfile Metrics endpoint. Log in
as the `admin` user with `adminpwd` as the password. You can see both the system and application
metrics in a text format.

To see only the application metrics, point your browser to `https://localhost:9443/metrics/application`.

See the following sample outputs for the `@Timed`, `@Gauge`, and `@Counted` metrics:

[source, role="no_copy"]
----
# TYPE application:inventory_properties_request_time_rate_per_second gauge
application:inventory_properties_request_time_rate_per_second 0.012564862395324394
# HELP application:inventory_properties_request_time_seconds Time needed to get the properties of a system from the given hostname
----
[source, role="no_copy"]
----
# TYPE application:inventory_size_guage gauge
# HELP application:inventory_size_guage Number of systems in the inventory
application:inventory_size_guage 1
----
[source, role="no_copy"]
----
# TYPE application:inventory_access_count counter
# HELP application:inventory_access_count Number of times the list of systems method is requested
application:inventory_access_count 1
----

When you're done with the application, stop the Open Liberty server with the following command:

```
mvn liberty:stop-server
```

Now, navigate back to the `start` directory to begin.

// =================================================================================================
// Adding MicroProfile Metrics to the inventory service
// =================================================================================================

== Adding MicroProfile Metrics to the inventory service

The MicroProfile Metrics API was added as a dependency to your `pom.xml` file. Look for the dependency with
the `org.eclipse.microprofile.metric` group ID. Add this dependency to use MicroProfile Metrics API
in your code to provide metrics from your microservices.

Next, create a `src/main/liberty/config/server.xml` file:

[source, xml, indent=0]
----
include::finish/src/main/liberty/config/server.xml[tags=server]
----

The `mpMetrics-1.0` feature enables MicroProfile Metrics support in Open Liberty. Note that this
feature requires SSL and the configuration has been provided for you.

The `quickStartSecurity` and `keyStore` configuration elements provide basic security to secure the
server. When you visit the `/metrics` endpoint, use the credentials defined in the server
configuration to log in to view the data.

// =================================================================================================
// Adding the annotations
// =================================================================================================

=== Adding the annotations

Create the `InventoryManager` class in the
`src/main/java/io/openliberty/guides/inventory/InventoryManager.java` file:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryManager.java[tags=InventoryManager]
----

Apply the `@Timed` annotation to the `get()` method to track how frequently the method is
invoked and also how long it takes for the invocation to complete. This annotation has these
metadata fields:

|===
|`name` | Optional. Use this field to name of the metric.
|`description` | Optional. Use this field to describe the purpose of the metric.
|===

Apply the `@Counted` annotation to the `list()` method to count how many times the
`http://localhost:9080/inventory/systems` URL is accessed. Note the additional metadata field:

|===
| `monotonic` | Set this annotation to `true` to count the total number of invocations of the
annotated method, which is the total number of times the inventory is accessed.
|===

Apply the `@Gauge` annotation to the `getTotal()` method to track the number of systems that are stored in
the inventory. Note that when the value of the gauge is retrieved, the underlying `getTotal()` method
is called to return the size of the inventory.

Additional information about these annotations, relevant metadata fields, and more are available at
the https://microprofile.io/project/eclipse/microprofile-metrics[MicroProfile website].

// =================================================================================================
// Building and running the application
// =================================================================================================

include::{common-includes}/mvnbuild.adoc[]

Point your browser to the `https://localhost:9443/metrics` URL to review the all available metrics
that have been enabled through MicroProfile Metrics. Log in with `admin` as your username and
`adminpwd` as your password. You see only the system metrics because the server just started,
and the `inventory` service has not been accessed.

Next, point your browser to the `http://localhost:9080/inventory/systems` URL. Reload the
`https://localhost:9443/metrics` URL, or access only the application metrics at the
`https://localhost:9443/metrics/application` URL.

include::{common-includes}/mvnpackage.adoc[]

// =================================================================================================
// Testing the metrics
// =================================================================================================

== Testing the metrics

You can test your application manually, but automated tests ensure code quality because they trigger a
failure whenever a code change introduces a defect. JUnit and the JAX-RS Client API provide a simple
environment for you to write tests.

First, create a test class in the `src/test/java/it/io/openliberty/guides/metrics/MetricsTest.java` file:

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/metrics/MetricsTest.java[tags=MetricsTest]
----

* The `testGetPropertiesTime()` test case validates the `@Timed` metric. It sends a request to the
`http://localhost:9080/inventory/systems/localhost` URL to access the `inventory` service, which adds
the `localhost` host to the inventory. Next, the test case makes a connection to the
`https://localhost:9443/metrics/application` URL to retrieve application metrics as plain text.
It then uses the `validateMetric()` method to assert whether the time that is needed to retrieve
the system properties for localhost is less than 4 seconds.

* The `testListCount()` test case validates the `@Counted` metric. The test case sends a request to the
`http://localhost:9080/inventory/systems` URL to retrieve the whole inventory, and then it asserts
that this endpoint is accessed only once.

* The `testInventorySize()` test case validates the `@Gauge` metric. The test case first ensures
that the localhost is in the inventory. It then looks for the `@Gauge` metric and asserts
that the inventory size is equal to 1.

The `oneTimeSetup()` method retrieves the port number for the server and builds a base URL string
to set up the tests. Apply the `@BeforeClass` annotation to this method to execute it before any of
the test cases.

The `setup()` method creates a JAX-RS client that makes HTTP requests to the `inventory` service.
Register this client with a `JsrJsonpProvider` JSON-P provider to process JSON resources. The
`teardown()` method destroys this client instance. Apply the `@Before` annotation so that a method
executes before a test case, and apply the `@After` annotation so that a method executes after a test
case. Apply these annotations to methods that are generally used to perform any setup and teardown tasks
before and after a test.

To execute the test cases in a particular order, put them in a `testSuite()` method.
Label the method with the `@Test` annotation, which automatically executes when your test class runs.

In addition, a few endpoint tests `src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointTest.java`
and `src/test/java/it/io/openliberty/guides/system/SystemEndpointTest.java` are provided for you to
test the basic functionality of the `inventory` and `system` services. If a test failure occurs, then you might have
introduced a bug into the code.

// =================================================================================================
// Running the tests
// =================================================================================================

include::{common-includes}/mvnverify.adoc[]

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.system.SystemEndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.4 sec - in it.io.openliberty.guides.system.SystemEndpointTest
Running it.io.openliberty.guides.metrics.MetricsTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.697 sec - in it.io.openliberty.guides.metrics.MetricsTest
Running it.io.openliberty.guides.inventory.InventoryEndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.264 sec - in it.io.openliberty.guides.inventory.InventoryEndpointTest

Results :

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
----

To see whether the tests detect a failure, go to the `MetricsTest.java` file and change any of the assertions
in the `validateMetric()` method. Rerun the Maven build. A test failure occurs.

// =================================================================================================
// Great work! You're done!
// =================================================================================================

== Great work! You're done!

You learned how to enable system and application metrics for microservices by using MicroProfile Metrics
and wrote tests to validate them.

include::{common-includes}/finish.adoc[]
