// Copyright (c) 2018, 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: microprofile-metrics
:page-layout: guide-multipane
:page-duration: 15 minutes
:page-releasedate: 2018-03-15
:page-guide-category: microprofile
:page-essential: false
:page-description: Learn how to use MicroProfile Metrics to provide system and application metrics from a microservice.
:page-tags: ['MicroProfile']
:page-permalink: /guides/{projectid}
:page-related-guides: ['rest-intro', 'microprofile-health', 'cdi-intro']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
:guide-author: Open Liberty
= Providing metrics from a microservice

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

You'll explore how to provide system and application metrics from a microservice with MicroProfile Metrics.

// =================================================================================================
// What you'll learn
// =================================================================================================

== What you'll learn

You will learn how to use MicroProfile Metrics to provide metrics from a microservice. You can monitor
metrics to determine the performance and health of a service. You can also use them to pinpoint issues,
collect data for capacity planning, or to decide when to scale a service to run with more or fewer
resources.

The application that you will work with is an `inventory` service that stores information about various
systems. The `inventory` service communicates with the `system` service on a particular host to retrieve
its system properties when necessary.

You will use annotations provided by MicroProfile Metrics to instrument the `inventory` service to
provide application-level metrics data. You will add counter, gauge, and timer metrics to the service.

You will also check well-known REST endpoints that are defined by MicroProfile Metrics to review
the metrics data collected. Monitoring agents can access these endpoints to collect metrics.

// =================================================================================================
// Getting Started
// =================================================================================================
[role=command]
include::{common-includes}/gitclone.adoc[]

// =================================================================================================
// Try what you'll build
// =================================================================================================

=== Try what you'll build

The `finish` directory contains the finished implementation for the application. You can try it out
before you build your own.

To try the application, navigate to the `finish` directory and run the following command:

[role=command]
-----------
mvn install liberty:start-server
-----------

Maven builds the application and runs it inside Open Liberty.

Point your browser to the http://localhost:9080/inventory/systems[http://localhost:9080/inventory/systems^] URL to access the `inventory`
service. Because you just started the application, the inventory is currently empty. Then, access the
http://localhost:9080/inventory/systems/localhost[http://localhost:9080/inventory/systems/localhost^] URL to add the localhost into the inventory.

Access the `inventory` service at the http://localhost:9080/inventory/systems[http://localhost:9080/inventory/systems^] URL at least once
for application metrics to be collected. Otherwise, the metrics will not appear.

Next, point your browser to the https://localhost:9443/metrics[http://localhost:9443/metrics^] MicroProfile Metrics endpoint. Log in
as the `admin` user with `adminpwd` as the password. You can see both the system and application
metrics in a text format.

To see only the application metrics, point your browser to https://localhost:9443/metrics/application[https://localhost:9443/metrics/application^].

See the following sample outputs for the `@Timed`, `@Gauge`, and `@Counted` metrics:

[role="no_copy"]
----
# TYPE application_inventoryProcessingTime_rate_per_second gauge
application_inventoryProcessingTime_rate_per_second{method="get"} 0.0019189661542898407
...
# TYPE application_inventoryProcessingTime_seconds summary
# HELP application_inventoryProcessingTime_seconds Time needed to process the inventory
application_inventoryProcessingTime_seconds_count{method="get"} 1
application_inventoryProcessingTime_seconds{method="get",quantile="0.5"} 0.127965469
...
# TYPE application_inventoryProcessingTime_rate_per_second gauge
application_inventoryProcessingTime_rate_per_second{method="list"} 0.0038379320982686884
...
# TYPE application_inventoryProcessingTime_seconds summary
# HELP application_inventoryProcessingTime_seconds Time needed to process the inventory
application_inventoryProcessingTime_seconds_count{method="list"} 2
application_inventoryProcessingTime_seconds{method="list",quantile="0.5"} 2.2185000000000002E-5
...
----
[role="no_copy"]
----
# TYPE application_inventorySizeGuage gauge
# HELP application_inventorySizeGuage Number of systems in the inventory
application_inventorySizeGuage 1
----
[role="no_copy"]
----
# TYPE application_inventoryAccessCount_total counter
# HELP application_inventoryAccessCount_total Number of times the list of systems method is requested
application_inventoryAccessCount_total 1
----

To see only the system metrics, point your browser to https://localhost:9443/metrics/base[https://localhost:9443/metrics/base^].

See the following sample output for the `@Gauge` and `@Counted` metrics:

[role="no_copy"]
----
# TYPE base:jvm_uptime_seconds gauge
# HELP base:jvm_uptime_seconds Displays the start time of the Java virtual machine in milliseconds. This attribute displays the approximate time when the Java virtual machine started.
base:jvm_uptime_seconds 39.025
----
[role="no_copy"]
----
# TYPE base_classloader_loadedClasses_count gauge
# HELP base_classloader_loadedClasses_count Displays the number of classes that are currently loaded in the Java virtual machine.
base_classloader_loadedClasses_count 11231
----

To see only the vendor metrics, point your browser to https://localhost:9443/metrics/vendor[https://localhost:9443/metrics/vendor^].

See the following sample output for the `@Gauge` and `@Counted` metrics:

[role="no_copy"]
----
# TYPE vendor_threadpool_size gauge
# HELP vendor_threadpool_size The size of the thread pool.
vendor_threadpool_size{pool="Default_Executor"} 32
----
[role="no_copy"]
----
# TYPE vendor_servlet_request_total counter
# HELP vendor_servlet_request_total The number of visits to this servlet since the start of the server.
vendor_servlet_request_total{servlet="microprofile_metrics_io_openliberty_guides_inventory_InventoryApplication"} 1
----

When you're done with the application, stop the Open Liberty server with the following command:

[role=command]
----
mvn liberty:stop-server
----

// =================================================================================================
// Adding MicroProfile Metrics to the inventory service
// =================================================================================================

== Adding MicroProfile Metrics to the inventory service

pom.xml
[source, xml, linenums, role='code_column']
----
include::finish/pom.xml[]
----

server.xml
[source, xml, linenums, role='code_column']
----
include::finish/src/main/liberty/config/server.xml[]
----

Navigate to the `start` directory to begin.

The MicroProfile Metrics API was added as a dependency to your [hotspot file=0]`pom.xml` file. This is the dependency with
the [hotspot=mpMetrics file=0]`mpMetrics` artifact ID. This dependency was added to use the MicroProfile Metrics API
in your code to provide metrics from your microservices.

[role="code_command hotspot file=1", subs="quotes"]
----
#Create the server configuration file.#
`src/main/liberty/config/server.xml`
----

The [hotspot=mpMetrics file=1]`mpMetrics` feature enables MicroProfile Metrics support in Open Liberty. Note that this
feature requires SSL and the configuration has been provided for you.

The [hotspot=quickStartSecurity file=1]`quickStartSecurity` and [hotspot=keyStore file=1]`keyStore` configuration elements provide basic security to secure the server. When you visit the `/metrics` endpoint, use the credentials defined in the server configuration to log in to view the data.

// =================================================================================================
// Adding the annotations
// =================================================================================================

=== Adding the annotations

[role="code_command hotspot", subs="quotes"]
----
#Create the `InventoryManager` class.#
`src/main/java/io/openliberty/guides/inventory/InventoryManager.java`
----

InventoryManager.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryManager.java[]
----

Apply the [hotspot=timedForGet]`@Timed` annotation to the [hotspot=get]`get()` method,
and apply the [hotspot=timedForList]`@Timed` annotation to the [hotspot=list]`list()` method.

This annotation has these metadata fields:

|===
|[hotspot=nameForGet hotspot=nameForList]`name` | Optional. Use this field to name the metric.
|[hotspot=tagForGet hotspot=tagForList]`tags` | Optional. Use this field to add tags to the metric with the same [hotspot=nameForGet hotspot=nameForList]`name`.
|[hotspot=absoluteForGet hotspot=absoluteForList]`absolute` | Optional. Use this field to determine whether the metric name is the exact name that is specified in the [hotspot=nameForGet hotspot=nameForList]`name` field or that is specified with the package prefix.
|[hotspot=desForGet hotspot=desForList]`description` | Optional. Use this field to describe the purpose of the metric.
|===

Both the [hotspot=get]`get()` and [hotspot=list]`list()` methods are annotated with the `@Timed` metric and have the same [hotspot=nameForGet hotspot=nameForList]`inventoryProcessingTime` name. The `@Timed` annotation tracks how frequently and how long it takes for the method invocation to complete. The [hotspot=tagForGet]`method=get` and [hotspot=tagForList]`method=list` tags add a dimension to the collected metric data for the inventory processing time in getting the system properties.

- The `method=get` processing time tag indicates the time to get the system properties from calling the `system` service.
- The `method=list` processing time tag indicates the time for the `inventory` service to list all of the system properties in the inventory.

The tags can then be queried with either the processing time for the [hotspot=get]`get()` method or the [hotspot=list]`list()` method or both.

Apply the [hotspot=countedForList]`@Counted` annotation to the [hotspot=list]`list()` method to count how many times the
`\http://localhost:9080/inventory/systems` URL is accessed monotonically, which is counting up sequentially.

Apply the [hotspot=gaugeForGetTotal]`@Gauge` annotation to the [hotspot=getTotal]`getTotal()` method to track the number of systems that are stored in
the inventory. Note that when the value of the gauge is retrieved, the underlying [hotspot=getTotal]`getTotal()` method
is called to return the size of the inventory. Note the additional metadata field:

|===
| [hotspot=unitForGetTotal]`unit` | Set the unit of the metric. If it is [hotspot=unitForGetTotal]`MetricUnits.NONE`, the metric name is used as is without appending the unit name, and no scaling is applied.
|===

Additional information about these annotations, relevant metadata fields, and more are available at
the https://openliberty.io/docs/ref/microprofile/3.0/#package=org/eclipse/microprofile/metrics/annotation/package-frame.html&class=org/eclipse/microprofile/metrics/annotation/package-summary.html[MicroProfile Metrics Annotation Javadoc^].


== Enabling vendor metrics for the micorservices

server.xml
[source, xml, linenums, role='code_column']
----
include::finish/src/main/liberty/config/server.xml[]
----

MicroProfile Metrics API implementors can provide vendor metrics in the same forms as the base and application outputs.
Liberty as a vendor supplies server component metrics when both the
[hotspot=mpMetrics]`mpMetrics` and [hotspot=monitor]`monitor` features are enabled in the [hotspot]`server.xml` configuration file.

You can see the vendor only metrics in the `metrics/vendor` endpoint.
You see metrics from the runtime components, such as Web Application, ThreadPool and Session Management.
Note that these metrics are specific to Liberty application server. Different vendor may provide other metrics.
Visit https://www.ibm.com/support/knowledgecenter/en/SSD28V_liberty/com.ibm.websphere.wlp.core.doc/ae/rwlp_monitor_metrics_rest_api.html[Liberty vendor metrics^] for more information.

// =================================================================================================
// Building and running the application
// =================================================================================================

[role=command]
include::{common-includes}/mvnbuild.adoc[]

Point your browser to the https://localhost:9443/metrics[https://localhost:9443/metrics^] URL to review the all available metrics
that have been enabled through MicroProfile Metrics. Log in with `admin` as your username and
`adminpwd` as your password. You see only the system and vendor metrics because the server just started,
and the `inventory` service has not been accessed.

Next, point your browser to the http://localhost:9080/inventory/systems[http://localhost:9080/inventory/systems^] URL. Reload the
https://localhost:9443/metrics[https://localhost:9443/metrics^] URL, or access only the application metrics at the
https://localhost:9443/metrics/application[https://localhost:9443/metrics/application^] URL.

You can see the system metrics in the https://localhost:9443/metrics/base[^] URL.
You can also see the vendor metrics in the https://localhost:9443/metrics/vendor[^] URL.

[role=command]
include::{common-includes}/mvncompile.adoc[]

// =================================================================================================
// Testing the metrics
// =================================================================================================

== Testing the metrics
MetricsTest.java
[source, java, linenums, role='code_column']
----
include::finish/src/test/java/it/io/openliberty/guides/metrics/MetricsTest.java[tags=MetricsTest]
----

InventoryManager.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryManager.java[]
----

You can test your application manually, but automated tests ensure code quality because they trigger a
failure whenever a code change introduces a defect. JUnit and the JAX-RS Client API provide a simple
environment for you to write tests.

[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `MetricsTest` class.#
`src/test/java/it/io/openliberty/guides/metrics/MetricsTest.java`
----

* The [hotspot=55-65 file=0]`testPropertiesRequestTimeMetric()` test case validates the [hotspot=timedForGet file=1]`@Timed` metric. It sends a request to the
`\http://localhost:9080/inventory/systems/localhost` URL to access the `inventory` service, which adds
the `localhost` host to the inventory. Next, the test case makes a connection to the
`\https://localhost:9443/metrics/application` URL to retrieve application metrics as plain text.
Then, it asserts whether the time that is needed to retrieve
the system properties for localhost is less than 4 seconds.

* The [hotspot=67-76 file=0]`testInventoryAccessCountMetric()` test case validates the [hotspot=countedForList file=1]`@Counted` metric. The test case sends a request to the
`\http://localhost:9080/inventory/systems` URL to retrieve the whole inventory, and then it asserts
that this endpoint is accessed only once.

* The [hotspot=78-87 file=0]`testInventorySizeGaugeMetric()` test case validates the [hotspot=gaugeForGetTotal file=1]`@Gauge` metric. The test case first ensures
that the localhost is in the inventory. It then looks for the [hotspot=gaugeForGetTotal file=1]`@Gauge` metric and asserts
that the inventory size is equal to 1.

The [hotspot=30-35 file=0]`oneTimeSetup()` method retrieves the port number for the server and builds a base URL string
to set up the tests. Apply the [hotspot=29 file=0]`@BeforeClass` annotation to this method to execute it before any of
the test cases.

The [hotspot=38-41]`setup()` method creates a JAX-RS client that makes HTTP requests to the `inventory` service.
Register this client with a [hotspot=40 file=0]`JsrJsonpProvider` JSON-P provider to process JSON resources. The
[hotspot=44-46]`teardown()` method destroys this client instance. Apply the [hotspot=37 file=0]`@Before` annotation so that a method
executes before a test case, and apply the [hotspot=43 file=0]`@After` annotation so that a method executes after a test
case. Apply these annotations to methods that are generally used to perform any setup and teardown tasks
before and after a test.

To execute the test cases in a particular order, put them in a [hotspot=49-53 file=0]`testSuite()` method.
Label the method with the [hotspot=48]`@Test` annotation, which automatically executes when your test class runs.

In addition, a few endpoint tests `src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointTest.java`
and `src/test/java/it/io/openliberty/guides/system/SystemEndpointTest.java` are provided for you to
test the basic functionality of the `inventory` and `system` services. If a test failure occurs, then you might have
introduced a bug into the code.

// =================================================================================================
// Running the tests
// =================================================================================================
[role=command]
include::{common-includes}/mvnverify.adoc[]

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.system.SystemEndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.4 sec - in it.io.openliberty.guides.system.SystemEndpointTest
Running it.io.openliberty.guides.metrics.MetricsTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.697 sec - in it.io.openliberty.guides.metrics.MetricsTest
Running it.io.openliberty.guides.inventory.InventoryEndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.264 sec - in it.io.openliberty.guides.inventory.InventoryEndpointTest

Results :

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
----

To see whether the tests detect a failure, go to the [hotspot file=0]`MetricsTest.java` file and change any of the assertions
in the test methods. Rerun the Maven build. A test failure occurs.

// =================================================================================================
// Great work! You're done!
// =================================================================================================

== Great work! You're done!

You learned how to enable system, application and vendor metrics for microservices by using MicroProfile Metrics
and wrote tests to validate them in Open Liberty.

include::{common-includes}/attribution.adoc[subs="attributes"]
